# Generated by Django 5.0.6 on 2025-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='interval',
            field=models.CharField(default='month', max_length=20),
        ),
    ]
