# Generated by Django 5.0.6 on 2025-12-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentplan_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='interval',
        ),
    ]
