# Generated by Django 5.0.6 on 2026-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_paymentplan_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic Website'), ('premium', 'Premium Website'), ('ecommerce', 'E-commerce Website'), ('enterprise', 'Enterprise Solution'), ('basic_pkg', 'Basic Package – Fast Start'), ('standard_pkg', 'Standard Package – Smart Growth'), ('advanced_pkg', 'Advanced Package – Scalable Foundation')], max_length=20),
        ),
    ]
