# Generated by Django 5.0.6 on 2026-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='payment_mode',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('payment', 'One-time Payment')], default='subscription', max_length=20),
        ),
    ]
