# Generated by Django 5.0.6 on 2026-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentplan_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter Package'), ('growth', 'Growth Package'), ('enterprise', 'Enterprise Package')], max_length=20),
        ),
    ]
