# Generated by Django 5.0.6 on 2026-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymentplan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter Package'), ('growth', 'Growth Package'), ('enterprise', 'Enterprise Package'), ('seo_intelligence', 'SEO Intelligence Suite')], max_length=20),
        ),
    ]
