# Generated by Django 5.0.6 on 2026-02-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0027_kpihistory_avg_phase_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_reviews', 'Google Reviews')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, help_text='API Key (placeholder)', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='API Secret (placeholder)', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Access Token (placeholder)')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh Token (placeholder)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialStreamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sentiment_score', models.FloatField(default=0.7, help_text='Minimum sentiment score to display (0.0 to 1.0)')),
                ('auto_approve', models.BooleanField(default=True, help_text='Automatically approve events with high sentiment score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_providers', models.ManyToManyField(blank=True, to='social_proof.socialprovider')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_stream_config', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('comment', 'Comment'), ('review', 'Review'), ('post', 'Post'), ('share', 'Share'), ('mention', 'Mention'), ('like', 'Like')], max_length=20)),
                ('external_id', models.CharField(help_text='ID from the external platform', max_length=255, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurred_at', models.DateTimeField(help_text='When the event actually happened on the platform')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='social_proof.socialprovider')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['provider', 'external_id'], name='social_proo_provide_d842c4_idx'), models.Index(fields=['sentiment_score'], name='social_proo_sentime_c88e9e_idx')],
            },
        ),
    ]
