# Generated by Django 5.0.6 on 2026-01-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_type',
            field=models.CharField(blank=True, choices=[('full_platform', 'Full Platform Services'), ('community', 'Community Services')], help_text='Selected service experience during onboarding', max_length=20, null=True),
        ),
    ]
