# Generated by Django 5.0.6 on 2026-01-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='community_needs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_description',
            field=models.CharField(blank=True, choices=[('personal', 'Personal project'), ('business', 'Business / Startup'), ('community', 'Community / Non-profit'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_timeline',
            field=models.CharField(blank=True, choices=[('immediately', 'Immediately'), ('1_month', 'Within 1 month'), ('3_months', 'Within 3 months'), ('exploring', 'Just exploring')], max_length=20),
        ),
    ]
