# Generated by Django 5.0.6 on 2026-04-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_service_description_usererp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usererp',
            name='description',
        ),
    ]
