# Generated by Django 5.0.6 on 2025-12-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='projectfeedback',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectfeedback',
            name='phase',
        ),
        migrations.DeleteModel(
            name='PhaseTask',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFeedback',
        ),
        migrations.DeleteModel(
            name='ProjectPhase',
        ),
    ]
