# Generated by Django 5.0.6 on 2025-12-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_phasetask_projectdeliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_feedback/'),
        ),
        migrations.CreateModel(
            name='ClientAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='client_assets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
        ),
    ]
