# Generated by Django 5.0.6 on 2025-12-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectfeedback_attachment_clientasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('IMPLEMENTED', 'Implemented')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.CharField(choices=[('PLANNING', 'Planning & Requirements'), ('DESIGN', 'Design Drafts'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing & QA'), ('LAUNCH', 'Launch'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase_type',
            field=models.CharField(choices=[('PLANNING', 'Planning & Requirements'), ('DESIGN', 'Design Drafts'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing & QA'), ('LAUNCH', 'Launch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
        ),
    ]
