# Generated by Django 5.0.6 on 2025-12-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_brandasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand_color',
            field=models.CharField(default='#0d6efd', help_text="Hex code for client's primary brand color", max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/'),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Design, Bug, Content', max_length=50),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.projectfeedback'),
        ),
    ]
