# Generated by Django 5.0.6 on 2025-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_brand_color_project_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'Under Review'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
    ]
