# Generated by Django 5.0.6 on 2025-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectphase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.CharField(choices=[('PLANNING', 'Planning & Requirements'), ('DESIGN', 'Design Drafts'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing & QA'), ('LAUNCH', 'Launch'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCEL_REQUESTED', 'Cancellation Requested'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20),
        ),
    ]
