# Generated by Django 5.0.6 on 2025-12-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeedback',
            name='is_admin_response',
            field=models.BooleanField(default=False),
        ),
    ]
