# Generated by Django 5.0.6 on 2025-12-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectfeedback_is_admin_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='progress',
            new_name='progress_percentage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website_type',
        ),
        migrations.RemoveField(
            model_name='projectfeedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectfeedback',
            name='parent',
        ),
        migrations.AddField(
            model_name='project',
            name='current_status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('DELIVERY', 'Delivery'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='brand_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.CharField(choices=[('PLANNING', 'Planning & Requirements'), ('DESIGN', 'Design Drafts'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing & QA'), ('LAUNCH', 'Launch'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
    ]
