# Generated by Django 5.0.6 on 2025-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectphase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeliverable',
            name='client_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('AWAITING_CLIENT', 'Awaiting Client Approval'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='client_visible_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='ready_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
