# Generated by Django 5.0.6 on 2025-12-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectphase_assignee_projectphase_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
    ]
