# Generated by Django 5.0.6 on 2025-12-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_assigned_team_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.CharField(choices=[('PLANNING', 'Planning & Requirements'), ('DESIGN', 'Design Drafts'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing & QA'), ('LAUNCH', 'Launch'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('DELIVERY', 'Delivery'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20),
        ),
    ]
