# Generated by Django 5.0.6 on 2025-12-25 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_phasetask_assigned_to_projectphase_assignee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. Designer, Developer, QA', max_length=100)),
                ('responsibility', models.TextField(blank=True, help_text='Short description of responsibilities')),
                ('is_visible', models.BooleanField(default=True, help_text='Visible to client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.projectphase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
