# Generated by Django 5.0.6 on 2025-12-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_phaseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaseassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
