# Generated by Django 5.0.6 on 2025-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_phaseassignment_end_date_phaseassignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agile_plan_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='agile_plan_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='agile_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Client Approval'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='Locked until Agile Plan is approved'),
        ),
    ]
