# Generated by Django 5.0.6 on 2025-12-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_agile_plan_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agile_plan_file',
            field=models.FileField(blank=True, null=True, upload_to='agile_plans/'),
        ),
    ]
