# Generated by Django 5.0.6 on 2025-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_agile_plan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phasetask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phasetask',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='phasetask',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('READY_FOR_REVIEW', 'Ready for Review'), ('COMPLETED', 'Completed')], default='TODO', max_length=20),
        ),
    ]
