# Generated by Django 5.0.6 on 2026-01-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_phasetask_description_phasetask_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('DELIVERY', 'Delivery'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('DELAYED', 'Delayed')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
    ]
