# Generated by Django 5.0.6 on 2026-01-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_kpihistory_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownotification',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
    ]
