# Generated by Django 5.0.6 on 2026-01-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_workflownotification_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpihistory',
            name='avg_phase_duration_days',
            field=models.FloatField(default=0.0),
        ),
    ]
