# Generated by Django 5.0.6 on 2026-08-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255, verbose_name='Website')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=10, verbose_name='Device')),
                ('performance_score', models.IntegerField(default=0, verbose_name='Performance Score')),
                ('fcp', models.FloatField(blank=True, null=True, verbose_name='First Contentful Paint (ms)')),
                ('lcp', models.FloatField(blank=True, null=True, verbose_name='Largest Contentful Paint (ms)')),
                ('inp', models.FloatField(blank=True, null=True, verbose_name='Interaction to Next Paint (ms)')),
                ('cls', models.FloatField(blank=True, null=True, verbose_name='Cumulative Layout Shift')),
                ('ttfb', models.FloatField(blank=True, null=True, verbose_name='Time to First Byte (ms)')),
                ('speed_index', models.FloatField(blank=True, null=True, verbose_name='Speed Index (ms)')),
                ('total_blocking_time', models.FloatField(blank=True, null=True, verbose_name='Total Blocking Time (ms)')),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('poor', 'Poor')], default='good', max_length=20, verbose_name='Status')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Performance Check',
                'verbose_name_plural': 'Performance Checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url', 'device'], name='platform_mo_url_95d37a_idx'), models.Index(fields=['-created_at'], name='platform_mo_created_0b4a23_idx')],
            },
        ),
    ]
