# Generated by Django 5.0.6 on 2025-12-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='serviceusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-created_at']},
        ),
    ]
