# Generated by Django 5.0.6 on 2025-12-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_chatbotmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceusage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
        migrations.DeleteModel(
            name='ServiceUsage',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
