# Generated by Django 5.0.6 on 2026-08-01 12:05

import branding.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('restaurant', 'Restaurant'), ('construction', 'Construction'), ('education', 'Education'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('saas', 'SaaS')], db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('industry', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='branding/collections/')),
                ('accent_color', models.CharField(default='#6366f1', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('ASSIGNED', 'Assigned'), ('DESIGNING', 'Designing'), ('REVISION', 'Revision'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=24)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('industry', models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('restaurant', 'Restaurant'), ('construction', 'Construction'), ('real_estate', 'Real Estate'), ('education', 'Education'), ('finance', 'Finance'), ('logistics', 'Logistics'), ('technology', 'Technology'), ('saas', 'SaaS'), ('retail', 'Retail'), ('travel', 'Travel'), ('automotive', 'Automotive'), ('energy', 'Energy'), ('other', 'Other')], default='', max_length=40)),
                ('website', models.URLField(blank=True, default='', max_length=300)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('business_description', models.TextField(blank=True, default='')),
                ('company_description', models.TextField(blank=True, default='')),
                ('target_audience', models.TextField(blank=True, default='')),
                ('brand_values', models.JSONField(blank=True, default=list)),
                ('preferred_colors', models.JSONField(blank=True, default=list)),
                ('current_branding', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='branding.brandcollection')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_design_assignments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=branding.models._upload_to)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('brand_guidelines', 'Brand Guidelines'), ('inspiration', 'Inspiration Image'), ('document', 'Document'), ('image', 'Image'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=30)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGE', 'Status Change'), ('ASSIGNMENT', 'Designer Assignment'), ('NOTE', 'Internal Note'), ('UPLOAD', 'File Upload')], default='NOTE', max_length=30)),
                ('action', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['status', 'created_at'], name='branding_br_status_4eea41_idx'),
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['request_number'], name='branding_br_request_75c732_idx'),
        ),
    ]
