# Generated by Django 5.0.6 on 2026-08-01 12:55

import branding.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingAssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=branding.models._upload_to)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='BrandingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_REQUEST', 'New Request'), ('DESIGNER_ASSIGNED', 'Designer Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('COMPLETED', 'Request Completed'), ('COMMENT', 'New Comment'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='brand_guidelines_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='business_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='color_palette',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='email_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='fonts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='letterhead_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='presentation_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='social_media_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='typography_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/collections/'),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=12),
        ),
        migrations.AlterField(
            model_name='brandingrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('ASSIGNED', 'Assigned'), ('DESIGNING', 'Designing'), ('WAITING_CLIENT', 'Waiting on Client'), ('REVISION', 'Revision'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=24),
        ),
        migrations.AlterField(
            model_name='brandingtimeline',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGE', 'Status Change'), ('ASSIGNMENT', 'Designer Assignment'), ('NOTE', 'Internal Note'), ('COMMENT', 'Client Comment'), ('UPLOAD', 'File Upload'), ('FILE_UPDATE', 'File Updated'), ('COLLECTION_CHANGE', 'Collection Changed'), ('PRIORITY_CHANGE', 'Priority Changed'), ('DELIVERY_CHANGE', 'Delivery Date Changed')], default='NOTE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['priority', 'status'], name='branding_br_priorit_84f2df_idx'),
        ),
        migrations.AddField(
            model_name='brandingassetversion',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='branding.brandingasset'),
        ),
        migrations.AddField(
            model_name='brandingassetversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_asset_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandingnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandingnotification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='branding.brandingrequest'),
        ),
        migrations.AddIndex(
            model_name='brandingnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='branding_br_recipie_8d3cab_idx'),
        ),
    ]
