# Generated by Django 5.0.6 on 2026-08-02 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_add_brandingmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_industry', models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('restaurant', 'Restaurant'), ('construction', 'Construction'), ('real_estate', 'Real Estate'), ('education', 'Education'), ('finance', 'Finance'), ('logistics', 'Logistics'), ('technology', 'Technology'), ('saas', 'SaaS'), ('retail', 'Retail'), ('travel', 'Travel'), ('automotive', 'Automotive'), ('energy', 'Energy'), ('other', 'Other')], default='', max_length=40)),
                ('default_country', models.CharField(blank=True, default='', max_length=120)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Per-channel notification toggles.')),
                ('saved_briefs', models.JSONField(blank=True, default=list, help_text='Partial wizard saves (up to 5).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_collections', models.ManyToManyField(blank=True, related_name='favorited_by', to='branding.brandcollection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branding Client Profile',
                'verbose_name_plural': 'Branding Client Profiles',
            },
        ),
    ]
