# Generated by Django 5.0.6 on 2026-08-03 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_brandingfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brandingmessage',
            index=models.Index(fields=['is_read_by_client', 'is_read_by_staff'], name='idx_msg_read_flags'),
        ),
        migrations.AddIndex(
            model_name='brandingmessage',
            index=models.Index(fields=['parent', 'created_at'], name='idx_msg_thread'),
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['company_name'], name='idx_branding_company'),
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['user', 'status'], name='idx_branding_user_status'),
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['designer', 'status'], name='idx_branding_designer_status'),
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['completed_at'], name='idx_branding_completed'),
        ),
        migrations.AddIndex(
            model_name='brandingrequest',
            index=models.Index(fields=['industry', 'status'], name='idx_branding_industry'),
        ),
        migrations.AddIndex(
            model_name='brandingtimeline',
            index=models.Index(fields=['request', 'event_type', 'created_at'], name='idx_timeline_event'),
        ),
    ]
