# Generated by Django 5.0.6 on 2026-08-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0007_add_webhook_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingasset',
            name='detected_mime',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='brandingasset',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brandingasset',
            name='sanitized_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brandingasset',
            name='scan_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandingasset',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=12),
        ),
        migrations.AddIndex(
            model_name='brandingasset',
            index=models.Index(fields=['request', 'asset_type'], name='idx_asset_request_type'),
        ),
        migrations.AddIndex(
            model_name='brandingasset',
            index=models.Index(fields=['scan_status'], name='idx_asset_scan_status'),
        ),
        migrations.AddIndex(
            model_name='brandingasset',
            index=models.Index(fields=['file_hash'], name='idx_asset_file_hash'),
        ),
    ]
