# Generated by Django 5.0.6 on 2026-08-03 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0008_enhance_asset_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingrequest',
            name='anonymized',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='consent_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='consent_data_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='consent_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='consent_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandingrequest',
            name='retention_period',
            field=models.CharField(choices=[('1y', '1 Year'), ('2y', '2 Years'), ('3y', '3 Years'), ('5y', '5 Years'), ('7y', '7 Years'), ('indefinite', 'Indefinite')], default='2y', max_length=12),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_processing', 'Data Processing'), ('marketing', 'Marketing Communications'), ('analytics', 'Analytics & Performance'), ('third_party', 'Third-Party Sharing')], max_length=20)),
                ('action', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='branding.brandingrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consent_type'], name='idx_consent_user_type'), models.Index(fields=['request', 'consent_type'], name='idx_consent_req_type')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready for Download'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=12)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=4)),
                ('file', models.FileField(blank=True, null=True, upload_to='branding/gdpr/exports/%Y/%m/')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_export_user_status')],
            },
        ),
        migrations.CreateModel(
            name='PrivacyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('cookie_policy', 'Cookie Policy')], max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_privacy_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'page'], name='idx_privacy_user_page')],
                'unique_together': {('user', 'page')},
            },
        ),
    ]
