# Generated by Django 5.0.6 on 2026-08-03 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0009_gdpr_compliance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('new_requests', models.PositiveIntegerField(default=0)),
                ('completed_requests', models.PositiveIntegerField(default=0)),
                ('archived_requests', models.PositiveIntegerField(default=0)),
                ('avg_completion_days', models.FloatField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_uploads', models.PositiveIntegerField(default=0)),
                ('satisfaction_avg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Aggregates',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('times_selected', models.PositiveIntegerField(default=0)),
                ('times_completed', models.PositiveIntegerField(default=0)),
                ('avg_satisfaction', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='branding.brandcollection')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('collection', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('assigned_count', models.PositiveIntegerField(default=0)),
                ('in_progress_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('avg_response_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_workload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Workloads',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
