# Generated by Django 5.0.6 on 2026-08-03 10:14

import branding.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0011_designernote_projectreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_submitted', models.BooleanField(default=False, help_text='True when designer submits for client review.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_drafts', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_drafts', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('design', 'Design Note'), ('decision', 'Design Decision'), ('research', 'Research'), ('inspiration', 'Inspiration'), ('client', 'Client Communication'), ('other', 'Other')], default='design', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('links', models.JSONField(blank=True, default=list, help_text='List of URL strings')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_notes', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('template', 'Template'), ('asset', 'Asset'), ('style_guide', 'Style Guide'), ('font', 'Font'), ('color_palette', 'Color Palette'), ('icon', 'Icon Set'), ('mockup', 'Mockup'), ('photo', 'Photo'), ('illustration', 'Illustration'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('shared_level', models.CharField(choices=[('team', 'Team Shared'), ('personal', 'Personal'), ('collection', 'Collection-Specific')], default='team', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='branding/resources/')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='branding/resources/thumbs/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='branding.brandcollection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('brief', 'Design Brief'), ('communication', 'Client Communication'), ('status_update', 'Status Update'), ('feedback', 'Feedback Request'), ('checklist', 'Checklist'), ('other', 'Other')], default='other', max_length=18)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names like ["client_name", "project_name"]')),
                ('is_team_shared', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=branding.models._draft_upload_to)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=6)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='branding.designdraft')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='PENDING', max_length=12)),
                ('client_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('client_answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('feedback_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='branding.feedbackrequest')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('research', 'Research'), ('concept', 'Concept Development'), ('design', 'Design'), ('revision', 'Revision'), ('delivery', 'Delivery'), ('meeting', 'Meeting'), ('other', 'Other')], default='design', max_length=12)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_timer_running', models.BooleanField(default=False)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
