# Generated by Django 5.0.6 on 2026-08-03 10:27

import branding.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0012_add_designer_workflow_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CritiqueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('prompts', models.JSONField(blank=True, default=list, help_text='List of critique prompt strings')),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critique_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tag', models.CharField(choices=[('general', 'General'), ('design', 'Design'), ('typography', 'Typography'), ('color', 'Color'), ('layout', 'Layout'), ('branding', 'Branding'), ('feedback', 'Client Feedback'), ('urgent', 'Urgent')], default='general', max_length=12)),
                ('annotation_x', models.PositiveIntegerField(blank=True, help_text='Screenshot annotation X position (%)', null=True)),
                ('annotation_y', models.PositiveIntegerField(blank=True, help_text='Screenshot annotation Y position (%)', null=True)),
                ('annotation_image', models.ImageField(blank=True, null=True, upload_to='branding/annotations/')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_comments', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='branding.designcomment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_comments', to='branding.brandingrequest')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Handoff'), ('HANDED_OFF', 'Handed Off'), ('ACKNOWLEDGED', 'Acknowledged')], default='DRAFT', max_length=14)),
                ('handoff_notes', models.TextField(blank=True, default='', help_text='Notes for the developer or client receiving the handoff')),
                ('style_guide_content', models.TextField(blank=True, default='', help_text='Auto-generated or manual style guide')),
                ('handed_off_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to=settings.AUTH_USER_MODEL)),
                ('handed_off_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handoffs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=branding.models._handoff_file_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('deliverable_type', models.CharField(choices=[('logo', 'Logo'), ('color_palette', 'Color Palette'), ('typography', 'Typography'), ('mockup', 'Mockup'), ('source_file', 'Source File'), ('export', 'Export'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=14)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='branding.designhandoff')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_deliverables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deliverable_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('brand', 'Brand Guidelines'), ('usage', 'Usage Instructions')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_notes', to=settings.AUTH_USER_MODEL)),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='branding.designhandoff')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('tips', 'Design Tips'), ('best_practices', 'Best Practices'), ('solutions', 'Common Solutions'), ('collection_insights', 'Collection Insights'), ('communication', 'Client Communication'), ('tools', 'Tools & Software'), ('process', 'Process & Workflow'), ('other', 'Other')], default='tips', max_length=20)),
                ('content', models.TextField()),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='branding.brandcollection')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=14)),
                ('message', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('critique_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='branding.critiquetemplate')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_reviews', to='branding.designdraft')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='branding.brandingrequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_sent', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional 1-5 rating', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='branding.peerreview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('branding', 'Branding'), ('logo', 'Logo Design'), ('packaging', 'Packaging'), ('print', 'Print'), ('digital', 'Digital'), ('illustration', 'Illustration'), ('other', 'Other')], default='branding', max_length=14)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='branding/showcase/covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('project_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_projects', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
