# Generated by Django 5.0.6 on 2026-08-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0013_add_collaboration_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdobeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adobe_user_id', models.CharField(max_length=100)),
                ('adobe_email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adobe_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adobe connections',
            },
        ),
        migrations.CreateModel(
            name='AdobeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(blank=True, default='', max_length=200)),
                ('library_name', models.CharField(blank=True, default='', max_length=200)),
                ('asset_id', models.CharField(max_length=200)),
                ('asset_name', models.CharField(max_length=300)),
                ('asset_type', models.CharField(choices=[('color', 'Color'), ('graphic', 'Graphic'), ('character_style', 'Character Style'), ('layer_style', 'Layer Style'), ('image', 'Image'), ('brush', 'Brush'), ('other', 'Other')], default='other', max_length=16)),
                ('preview_url', models.URLField(blank=True, default='', max_length=500)),
                ('creation_url', models.URLField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adobe_assets', to='branding.brandingrequest')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adobe_assets', to='branding.adobeconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetOrganizerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('logo', 'Logo'), ('icon', 'Icon'), ('pattern', 'Pattern'), ('texture', 'Texture'), ('other', 'Other')], default='other', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='branding/organizer/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='branding/organizer/thumbs/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('folder', models.CharField(blank=True, default='General', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_items', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_items', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['folder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandGuidelineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=200)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('WARN', 'Warning'), ('FAIL', 'Fail')], default='PASS', max_length=4)),
                ('details', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideline_checks', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideline_checks', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('apple', 'Apple Calendar')], default='google', max_length=10)),
                ('calendar_id', models.CharField(max_length=300)),
                ('calendar_name', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_deadlines', models.BooleanField(default=True)),
                ('sync_meetings', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calendar connections',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('deadline', 'Deadline'), ('meeting', 'Meeting'), ('milestone', 'Milestone'), ('review', 'Review')], default='deadline', max_length=10)),
                ('external_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='branding.calendarconnection')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('colors', models.JSONField(default=list, help_text='List of hex color strings')),
                ('is_public', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_palettes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_palettes', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FigmaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figma_user_id', models.CharField(max_length=100)),
                ('figma_email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='figma_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Figma connections',
            },
        ),
        migrations.CreateModel(
            name='FigmaDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figma_file_key', models.CharField(max_length=200)),
                ('figma_file_name', models.CharField(max_length=300)),
                ('figma_node_id', models.CharField(blank=True, default='', max_length=100)),
                ('figma_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('version', models.CharField(blank=True, default='', max_length=100)),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Synced'), ('OUTDATED', 'Outdated'), ('ERROR', 'Error')], default='SYNCED', max_length=10)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='branding.figmaconnection')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figma_designs', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
        migrations.CreateModel(
            name='FigmaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figma_comment_id', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('figma_created_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figma_comments', to='branding.figmadesign')),
            ],
            options={
                'ordering': ['-figma_created_at'],
            },
        ),
        migrations.CreateModel(
            name='FontEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('weights', models.JSONField(blank=True, default=list, help_text='Available weights')),
                ('styles', models.JSONField(blank=True, default=list, help_text='Available styles')),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonts', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlackConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=100)),
                ('workspace_name', models.CharField(max_length=200)),
                ('bot_token', models.CharField(max_length=500)),
                ('bot_user_id', models.CharField(blank=True, default='', max_length=100)),
                ('channel_id', models.CharField(blank=True, default='', max_length=100)),
                ('channel_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_assignments', models.BooleanField(default=True)),
                ('notify_deadlines', models.BooleanField(default=True)),
                ('notify_feedback', models.BooleanField(default=True)),
                ('notify_daily_digest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Slack connections',
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('assignment', 'Assignment'), ('deadline', 'Deadline'), ('feedback', 'Feedback'), ('digest', 'Daily Digest'), ('status', 'Status Update')], max_length=10)),
                ('slack_message_ts', models.CharField(blank=True, default='', max_length=50)),
                ('channel', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='branding.slackconnection')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_messages', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
