# Generated by Django 5.0.6 on 2026-08-03 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0014_add_designer_integrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stats_quick', 'Quick Stats'), ('stats_projects', 'Project Stats'), ('stats_team', 'Team Stats'), ('stats_designer', 'Designer Stats'), ('chart_status', 'Status Distribution'), ('chart_timeline', 'Timeline Chart'), ('chart_workload', 'Workload Chart'), ('chart_performance', 'Performance Chart'), ('table_recent', 'Recent Requests'), ('table_team', 'Team Performance'), ('table_deadlines', 'Upcoming Deadlines'), ('table_timesheet', 'My Timesheet'), ('feed_activity', 'Recent Activity'), ('feed_notifications', 'Notifications'), ('feed_messages', 'Messages'), ('feed_calendar', 'Calendar Events'), ('tools_shortcuts', 'Quick Tools'), ('tools_timer', 'Timer'), ('tools_figma', 'Figma'), ('tools_adobe', 'Adobe CC')], max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='fa-solid fa-puzzle-piece', max_length=60)),
                ('category', models.CharField(choices=[('stats', 'Statistics'), ('chart', 'Charts'), ('table', 'Tables'), ('feed', 'Feeds'), ('tools', 'Tools')], default='stats', max_length=30)),
                ('default_width', models.PositiveSmallIntegerField(default=1, help_text='Grid columns (1-4)')),
                ('default_height', models.PositiveSmallIntegerField(default=1, help_text='Grid rows (1-3)')),
                ('min_width', models.PositiveSmallIntegerField(default=1)),
                ('min_height', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoleSwitchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(max_length=20)),
                ('to_role', models.CharField(max_length=20)),
                ('switched_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_switch_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-switched_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('default', 'Default'), ('compact', 'Compact'), ('wide', 'Wide'), ('fullscreen', 'Full Screen')], default='default', max_length=20)),
                ('columns', models.PositiveSmallIntegerField(default=3, help_text='Number of grid columns (2-4)')),
                ('show_sidebar', models.BooleanField(default=True)),
                ('show_header', models.BooleanField(default=True)),
                ('compact_mode', models.BooleanField(default=False)),
                ('active_role_view', models.CharField(blank=True, default='', help_text='Current role perspective', max_length=20)),
                ('allow_role_switch', models.BooleanField(default=False, help_text='Can switch between role views')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Dashboard',
                'verbose_name_plural': 'Staff Dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('col', models.PositiveSmallIntegerField(default=0, help_text='Grid column position (0-indexed)')),
                ('row', models.PositiveSmallIntegerField(default=0, help_text='Grid row position (0-indexed)')),
                ('width', models.PositiveSmallIntegerField(default=1, help_text='Grid columns span')),
                ('height', models.PositiveSmallIntegerField(default=1, help_text='Grid rows span')),
                ('is_visible', models.BooleanField(default=True)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget-specific configuration')),
                ('visible_roles', models.JSONField(blank=True, default=list, help_text='Roles that see this widget')),
                ('refresh_interval', models.PositiveIntegerField(default=0, help_text='Auto-refresh seconds (0=off)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='branding.staffdashboard')),
                ('widget_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='branding.widgetdefinition')),
            ],
            options={
                'ordering': ['row', 'col'],
                'unique_together': {('dashboard', 'col', 'row')},
            },
        ),
    ]
