# Generated by Django 5.0.6 on 2026-08-03 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0015_add_unified_staff_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('brief_review', 'Initial Brief Review'), ('concept', 'Concept Development'), ('first_presentation', 'First Presentation'), ('client_feedback', 'Client Feedback'), ('revisions', 'Revisions'), ('question_phase', 'Question Phase'), ('final_presentation', 'Final Presentation'), ('completion', 'Project Completion')], default='brief_review', max_length=30)),
                ('stage_started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_stages', models.JSONField(blank=True, default=list)),
                ('escalation_threshold_days', models.PositiveIntegerField(default=5, help_text='Days before escalation alert')),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('addressed', 'Addressed'), ('resolved', 'Resolved')], default='new', max_length=15)),
                ('category', models.CharField(choices=[('brand_direction', 'Brand Direction'), ('color', 'Color'), ('typography', 'Typography'), ('layout', 'Layout'), ('imagery', 'Imagery'), ('tone', 'Tone & Voice'), ('target_audience', 'Target Audience'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('linked_element', models.CharField(blank=True, default='', help_text='Design element reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback_items', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_feedback', to='branding.brandingrequest')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='branding.projectworkflow')),
            ],
            options={
                'verbose_name_plural': 'Feedback items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, upload_to='design_iterations/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='design_iterations/thumbs/%Y/%m/')),
                ('change_notes', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_iterations', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_iterations', to='branding.brandingrequest')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='branding.projectworkflow')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('brand_direction', 'Brand Direction'), ('color', 'Color'), ('typography', 'Typography'), ('layout', 'Layout'), ('imagery', 'Imagery'), ('tone', 'Tone & Voice'), ('target_audience', 'Target Audience'), ('general', 'General')], default='general', max_length=20)),
                ('decision', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='branding.brandingrequest')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='branding.projectworkflow')),
            ],
            options={
                'verbose_name_plural': 'Decision logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('message', 'Message'), ('question', 'Question'), ('feedback', 'Feedback'), ('approval', 'Approval'), ('revision', 'Revision Request'), ('note', 'Internal Note')], default='message', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('is_from_client', models.BooleanField(default=False)),
                ('response_time_seconds', models.PositiveIntegerField(default=0)),
                ('is_action_item', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_communications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_communications', to='branding.brandingrequest')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='branding.projectworkflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('brand_direction', 'Brand Direction'), ('color', 'Color'), ('typography', 'Typography'), ('layout', 'Layout'), ('imagery', 'Imagery'), ('tone', 'Tone & Voice'), ('target_audience', 'Target Audience'), ('general', 'General')], default='general', max_length=20)),
                ('question', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('answer', models.TextField(blank=True, default='')),
                ('is_answered', models.BooleanField(default=False)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_questions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='branding.projectworkflow')),
            ],
            options={
                'ordering': ['-is_required', '-asked_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('brief_review', 'Initial Brief Review'), ('concept', 'Concept Development'), ('first_presentation', 'First Presentation'), ('client_feedback', 'Client Feedback'), ('revisions', 'Revisions'), ('question_phase', 'Question Phase'), ('final_presentation', 'Final Presentation'), ('completion', 'Project Completion')], max_length=30)),
                ('to_stage', models.CharField(choices=[('brief_review', 'Initial Brief Review'), ('concept', 'Concept Development'), ('first_presentation', 'First Presentation'), ('client_feedback', 'Client Feedback'), ('revisions', 'Revisions'), ('question_phase', 'Question Phase'), ('final_presentation', 'Final Presentation'), ('completion', 'Project Completion')], max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_moves', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='branding.projectworkflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
