# Generated by Django 5.0.6 on 2026-08-03 12:14

import branding.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0016_add_designer_workflow_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptPresentationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('meeting_url', models.URLField(blank=True, help_text='Video call link')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('recording_url', models.URLField(blank=True, help_text='Recording link')),
                ('recording_file', models.FileField(blank=True, null=True, upload_to=branding.models.concept_upload_path)),
                ('notes_taken', models.TextField(blank=True)),
                ('realtime_feedback', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_sessions', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptRefinement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=15)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_refinements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptRefinementIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(help_text='What was changed')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to=branding.models.concept_upload_path)),
                ('after_image', models.ImageField(blank=True, null=True, upload_to=branding.models.concept_upload_path)),
                ('client_approved', models.BooleanField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('refinement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='branding.conceptrefinement')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DesignConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Designer explanation of the concept')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('presented', 'Presented'), ('in_review', 'In Review'), ('client_selected', 'Client Selected'), ('designer_recommended', 'Designer Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=25)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=branding.models.concept_upload_path)),
                ('color_palette', models.JSONField(blank=True, default=list, help_text='List of hex color codes')),
                ('fonts', models.JSONField(blank=True, default=list, help_text='List of font names used')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Concept type tags')),
                ('layout_description', models.TextField(blank=True, help_text='Description of layout approach')),
                ('pros', models.JSONField(blank=True, default=list, help_text='Pros of this concept')),
                ('cons', models.JSONField(blank=True, default=list, help_text='Cons of this concept')),
                ('feature_checklist', models.JSONField(blank=True, default=list, help_text='Feature checklist items')),
                ('designer_ranking', models.PositiveIntegerField(blank=True, help_text='Designer recommended ranking (1 = top pick)', null=True)),
                ('client_ranking', models.PositiveIntegerField(blank=True, help_text='Client ranking (1 = favorite)', null=True)),
                ('is_designer_top_pick', models.BooleanField(default=False)),
                ('is_client_favorite', models.BooleanField(default=False)),
                ('combine_with', models.JSONField(blank=True, default=list, help_text='List of concept IDs to combine elements from')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presented_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designed_concepts', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['designer_ranking', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptStickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('x_position', models.FloatField(help_text='X coordinate as percentage (0-100)')),
                ('y_position', models.FloatField(help_text='Y coordinate as percentage (0-100)')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange')], default='yellow', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_sticky_notes', to=settings.AUTH_USER_MODEL)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_notes', to='branding.designconcept')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conceptrefinement',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinements', to='branding.designconcept'),
        ),
        migrations.CreateModel(
            name='ConceptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=branding.models.concept_image_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image_type', models.CharField(choices=[('layout', 'Layout'), ('mockup', 'Mockup'), ('detail', 'Detail'), ('variation', 'Variation'), ('reference', 'Reference')], default='mockup', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_images', to='branding.designconcept')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(help_text='Overall concept rating 1-5 stars')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('feedback_text', models.TextField()),
                ('strengths', models.TextField(blank=True, help_text='What works well')),
                ('improvements', models.TextField(blank=True, help_text='What could be improved')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to designer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='branding.designconcept')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptDecisionTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_decision_trail', to='branding.brandingrequest')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_trail', to='branding.designconcept')),
            ],
            options={
                'verbose_name_plural': 'Concept decision trails',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConceptDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('favorite', 'Marked as Favorite'), ('recommended', 'Designer Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('combined', 'Combining with Other Concepts')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('combine_with_concepts', models.JSONField(blank=True, default=list, help_text='Concept IDs to combine if decision is "combined"')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_decisions', to=settings.AUTH_USER_MODEL)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='branding.designconcept')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Concept Comparison', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_comparisons', to='branding.brandingrequest')),
                ('concepts', models.ManyToManyField(related_name='comparisons', to='branding.designconcept')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('comment', 'Comment'), ('question', 'Question'), ('suggestion', 'Suggestion'), ('issue', 'Issue'), ('praise', 'Praise')], default='comment', max_length=20)),
                ('text', models.TextField()),
                ('x_position', models.FloatField(help_text='X coordinate as percentage (0-100)')),
                ('y_position', models.FloatField(help_text='Y coordinate as percentage (0-100)')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_annotations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_annotations', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, help_text='If attached to a specific supporting image', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branding.conceptimage')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='branding.designconcept')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptElementRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('logo', 'Logo'), ('colors', 'Color Palette'), ('typography', 'Typography'), ('layout', 'Layout'), ('imagery', 'Imagery'), ('overall', 'Overall')], max_length=20)),
                ('score', models.PositiveIntegerField(help_text='Rating 1-5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_ratings', to=settings.AUTH_USER_MODEL)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_ratings', to='branding.designconcept')),
            ],
            options={
                'unique_together': {('concept', 'client', 'element')},
            },
        ),
    ]
