# Generated by Django 5.0.6 on 2026-08-03 13:00

import branding.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0017_add_concept_presentation_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('description', models.TextField(blank=True, help_text='Additional context or help text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('preference_scale', 'Preference Scale (1-10)'), ('yes_no', 'Yes/No'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('color_picker', 'Color Picker'), ('font_selection', 'Font Selection'), ('image_upload', 'Image Upload (Inspiration)'), ('rank_order', 'Rank Ordering'), ('rating', 'Star Rating (1-5)')], max_length=20)),
                ('category', models.CharField(choices=[('logo', 'Logo Design'), ('colors', 'Color Palette'), ('typography', 'Typography'), ('layout', 'Layout'), ('imagery', 'Imagery'), ('tone', 'Tone & Voice'), ('direction', 'Overall Direction'), ('general', 'General')], default='general', max_length=20)),
                ('phase', models.CharField(choices=[('discovery', 'Brand Discovery'), ('concept_direction', 'Concept Direction'), ('color_typography', 'Color & Typography'), ('layout_structure', 'Layout & Structure'), ('final_polish', 'Final Polish')], default='discovery', max_length=25)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('nice_to_know', 'Nice to Know')], default='important', max_length=15)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for multiple choice / rank order')),
                ('scale_min', models.PositiveIntegerField(default=1, help_text='Min value for preference scale')),
                ('scale_max', models.PositiveIntegerField(default=10, help_text='Max value for preference scale')),
                ('scale_labels', models.JSONField(blank=True, default=dict, help_text='Labels for scale endpoints')),
                ('allow_multiple', models.BooleanField(default=False, help_text='Allow multiple selections')),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('max_file_size_mb', models.PositiveIntegerField(default=5, help_text='Max upload size for image questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_colors', models.JSONField(blank=True, default=list)),
                ('preferred_fonts', models.JSONField(blank=True, default=list)),
                ('preferred_styles', models.JSONField(blank=True, default=list)),
                ('preferred_tones', models.JSONField(blank=True, default=list)),
                ('preferred_layouts', models.JSONField(blank=True, default=list)),
                ('avg_scale_scores', models.JSONField(blank=True, default=dict)),
                ('common_keywords', models.JSONField(blank=True, default=list)),
                ('total_questionnaires_completed', models.PositiveIntegerField(default=0)),
                ('avg_completion_time_hours', models.FloatField(default=0)),
                ('contradictions', models.JSONField(blank=True, default=list)),
                ('patterns', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Client preference profiles',
            },
        ),
        migrations.CreateModel(
            name='QuestionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does Not Equal'), ('contains', 'Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than')], default='equals', max_length=20)),
                ('condition_value', models.CharField(help_text='Expected answer value', max_length=500)),
                ('depends_on', models.ForeignKey(help_text='...this question has answer...', on_delete=django.db.models.deletion.CASCADE, related_name='conditions_to', to='branding.question')),
                ('question', models.ForeignKey(help_text='This question is shown when...', on_delete=django.db.models.deletion.CASCADE, related_name='conditions_from', to='branding.question')),
            ],
            options={
                'verbose_name_plural': 'Question conditions',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('phase', models.CharField(choices=[('discovery', 'Brand Discovery'), ('concept_direction', 'Concept Direction'), ('color_typography', 'Color & Typography'), ('layout_structure', 'Layout & Structure'), ('final_polish', 'Final Polish')], default='discovery', max_length=25)),
                ('share_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('send_email', models.BooleanField(default=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_reminder_count', models.PositiveIntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_questionnaires', to=settings.AUTH_USER_MODEL)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_questionnaires', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='branding.brandingrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='branding.questionnaire'),
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('category', models.CharField(choices=[('logo', 'Logo Design'), ('colors', 'Color Palette'), ('typography', 'Typography'), ('layout', 'Layout'), ('imagery', 'Imagery'), ('tone', 'Tone & Voice'), ('direction', 'Overall Direction'), ('general', 'General')], default='general', max_length=20)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('nice_to_know', 'Nice to Know')], default='critical', max_length=15)),
                ('options', models.JSONField(blank=True, default=list, help_text='Decision options to choose from')),
                ('selected_option', models.CharField(blank=True, max_length=500)),
                ('client_notes', models.TextField(blank=True)),
                ('designer_notes', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_points', to='branding.brandingrequest')),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_points', to='branding.questionnaire')),
            ],
            options={
                'ordering': ['status', '-importance', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('discovery', 'Brand Discovery'), ('concept_direction', 'Concept Direction'), ('color_typography', 'Color & Typography'), ('layout_structure', 'Layout & Structure'), ('final_polish', 'Final Polish')], max_length=25)),
                ('industry', models.CharField(blank=True, help_text='Specific to industry, or blank for all', max_length=50)),
                ('questions_data', models.JSONField(default=list, help_text='List of question dicts: [{text, type, category, importance, required, options, ...}]')),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, help_text='Specific to collection, or blank for all', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branding.brandcollection')),
            ],
            options={
                'ordering': ['phase', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=branding.models.answer_upload_path)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('rank_order', models.JSONField(blank=True, default=list)),
                ('color_value', models.CharField(blank=True, max_length=7)),
                ('font_choice', models.CharField(blank=True, max_length=100)),
                ('scale_value', models.PositiveIntegerField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='branding.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('question', 'client', 'version')},
            },
        ),
    ]
