# Generated by Django 5.0.6 on 2026-08-03 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0018_add_questionnaire_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('template_type', models.CharField(choices=[('logo', 'Logo'), ('business_card', 'Business Card'), ('letterhead', 'Letterhead'), ('envelope', 'Envelope'), ('presentation', 'Presentation'), ('social_media', 'Social Media'), ('email_signature', 'Email Signature'), ('brand_guidelines', 'Brand Guidelines'), ('brochure', 'Brochure'), ('flyer', 'Flyer'), ('packaging', 'Packaging'), ('merchandise', 'Merchandise'), ('signage', 'Signage'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='branding/collection_templates/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='branding/collection_templates/thumbs/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='branding.brandcollection')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
