# Generated by Django 5.0.6 on 2026-08-07 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0019_collectiontemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('description', models.TextField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=80)),
                ('client_name', models.CharField(blank=True, default='', max_length=120)),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('color_palette', models.JSONField(blank=True, default=list)),
                ('fonts', models.JSONField(blank=True, default=list)),
                ('accent_color', models.CharField(default='#6366f1', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('designer', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DesignerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('color_palette', 'Color Palette'), ('typography', 'Typography'), ('reference', 'Design Reference'), ('template', 'Template'), ('file', 'Creative File'), ('image', 'Image'), ('document', 'Document')], default='file', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='designer/collections/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='designer/collections/thumbs/%Y/%m/')),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('color_hex', models.CharField(blank=True, default='', max_length=9)),
                ('font_name', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='branding.designercollection')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
