# Generated by Django 5.0.6 on 2026-08-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0020_designercollection_designerasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='designresource',
            name='color_hex',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='designresource',
            name='designer_collection',
            field=models.ForeignKey(blank=True, help_text='Designer-owned collection this resource belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='branding.designercollection'),
        ),
        migrations.AddField(
            model_name='designresource',
            name='font_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
