# Generated by Django 5.0.6 on 2026-08-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0021_designresource_color_hex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designercollection',
            name='brand_guidelines_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='business_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='email_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published to client library'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='letterhead_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='presentation_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='social_media_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='designercollection',
            name='typography_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer/collections/previews/%Y/%m/'),
        ),
    ]
