# Generated by Django 5.0.6 on 2026-07-27 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forumpost',
            name='forum_forum_status_14ff61_idx',
        ),
        migrations.RemoveIndex(
            model_name='forumpost',
            name='forum_forum_author__e19f06_idx',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Author can hide post from public listing'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('reported', 'Reported')], default='approved', max_length=20),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['status', 'moderation_status', '-created_at'], name='forum_forum_status_326fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', 'status', '-created_at'], name='forum_forum_author__93ffd4_idx'),
        ),
    ]
