# Generated by Django 5.0.6 on 2026-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpaworkflow',
            name='step_definitions',
            field=models.JSONField(default=list, help_text="List of step names, e.g. ['Init', 'Process', 'Cleanup']"),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage 0-100'),
        ),
    ]
