# Generated by Django 5.0.6 on 2026-01-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_dashboard', '0002_rpaworkflow_step_definitions_workflowrun_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
