# Generated by Django 5.2.8 on 2025-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='CSS class or icon name (e.g., Bootstrap icon)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
