# Generated by Django 5.0.6 on 2026-01-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_posts', models.IntegerField(default=0)),
                ('avg_engagement', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, unique=True)),
                ('total_posts_tracked', models.IntegerField(default=0)),
                ('avg_engagement_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('platform_id', models.CharField(max_length=100, unique=True)),
                ('followers_count', models.BigIntegerField(default=0)),
                ('following_count', models.BigIntegerField(default=0)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=20)),
                ('post_url', models.URLField(max_length=500, unique=True)),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('views', models.BigIntegerField(default=0)),
                ('engagement_score', models.BigIntegerField(default=0)),
                ('classification', models.CharField(choices=[('viral', 'Viral'), ('normal', 'Normal'), ('low', 'Low Engagement')], default='normal', max_length=20)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='posts', to='services.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='services.socialuser')),
            ],
        ),
    ]
