# Generated by Django 5.0.6 on 2026-07-31 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
        migrations.CreateModel(
            name='SocialTrackingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_input', models.CharField(max_length=255)),
                ('normalized_handle', models.CharField(db_index=True, max_length=255)),
                ('detected_platform', models.CharField(blank=True, max_length=20)),
                ('selected_platforms', models.JSONField(blank=True, default=list)),
                ('total_followers', models.BigIntegerField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('data_source', models.CharField(default='database', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('unavailable', 'Unavailable'), ('error', 'Error')], default='success', max_length=20)),
                ('synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_tracking_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-synced_at', '-id'],
            },
        ),
    ]
