# Generated by Django 5.0.6 on 2026-02-03 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('personal', 'Personal website'), ('business', 'Business website'), ('startup', 'Startup / SaaS'), ('store', 'Online store'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=20)),
                ('website_goals', models.JSONField(default=list, help_text='List of selected goals')),
                ('required_pages', models.JSONField(default=list, help_text='List of required pages')),
                ('style_preference', models.CharField(blank=True, max_length=100)),
                ('color_preference', models.CharField(blank=True, max_length=100)),
                ('reference_websites', models.TextField(blank=True)),
                ('future_vision', models.JSONField(default=list, help_text='List of future vision items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
