# Generated by Django 5.0.6 on 2026-07-27 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('projects', '0027_kpihistory_avg_phase_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-plus-circle', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('web', 'Website Development'), ('brand', 'Brand & Design'), ('marketing', 'Marketing & SEO'), ('consulting', 'Consulting')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-cube', help_text='Font Awesome icon class', max_length=50)),
                ('estimated_duration', models.CharField(default='2-4 weeks', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('complexity_weight', models.PositiveIntegerField(default=1, help_text='1-10 scale for estimation')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('completed_steps', models.JSONField(default=list, help_text='List of completed step numbers')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('business_description', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('business_goals', models.JSONField(default=list)),
                ('current_website', models.URLField(blank=True)),
                ('competitors', models.TextField(blank=True, help_text='One per line')),
                ('social_media_links', models.JSONField(default=dict, help_text='Platform: URL mapping')),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('required_pages', models.JSONField(default=list)),
                ('special_features', models.JSONField(default=list)),
                ('design_style', models.CharField(blank=True, max_length=100)),
                ('preferred_colors', models.CharField(blank=True, max_length=255)),
                ('typography_style', models.CharField(blank=True, max_length=100)),
                ('reference_websites', models.TextField(blank=True)),
                ('inspiration_images', models.JSONField(default=list)),
                ('uploaded_logo', models.ImageField(blank=True, null=True, upload_to='onboarding/logos/')),
                ('uploaded_brand_guide', models.FileField(blank=True, null=True, upload_to='onboarding/brand_guides/')),
                ('selected_features', models.JSONField(default=list)),
                ('estimation_data', models.JSONField(default=dict, help_text='AI/rule-based estimation results')),
                ('recommended_package', models.CharField(blank=True, max_length=50)),
                ('selected_package', models.CharField(blank=True, max_length=50)),
                ('selected_addons', models.JSONField(default=list)),
                ('addons_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proposal_data', models.JSONField(default=dict)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('payment_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
                ('selected_services', models.ManyToManyField(blank=True, related_name='sessions', to='community.servicetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
