# Generated by Django 5.0.6 on 2026-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_onboardingaddon_servicetype_onboardingsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingsession',
            name='current_website',
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='accent_color',
            field=models.CharField(blank=True, default='#8b5cf6', max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='existing_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='inspiration_sites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='integrations',
            field=models.TextField(blank=True, help_text='Comma-separated third-party integrations'),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='primary_color',
            field=models.CharField(blank=True, default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='project_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='target_launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
