# Generated by Django 5.0.6 on 2026-07-27 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_onboardingsession_current_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Brand/Business Name')),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Tagline or Slogan')),
                ('description', models.TextField(blank=True, verbose_name='Brand Description')),
                ('target_audience', models.TextField(blank=True)),
                ('personality', models.CharField(choices=[('professional', 'Professional & Corporate'), ('playful', 'Playful & Creative'), ('luxurious', 'Luxurious & Premium'), ('minimal', 'Minimal & Clean'), ('edgy', 'Edgy & Bold'), ('friendly', 'Friendly & Approachable'), ('innovative', 'Innovative & Tech-forward')], default='professional', max_length=30)),
                ('brand_voice', models.CharField(choices=[('formal', 'Formal & Authoritative'), ('conversational', 'Conversational & Friendly'), ('humorous', 'Humorous & Witty'), ('inspirational', 'Inspirational & Motivating'), ('direct', 'Direct & Professional'), ('storytelling', 'Storytelling & Narrative')], default='professional', max_length=30, verbose_name='Brand Voice')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('accent_color', models.CharField(default='#10b981', max_length=7)),
                ('typography_preference', models.CharField(blank=True, max_length=100)),
                ('logo_description', models.TextField(blank=True, help_text='Describe your ideal logo')),
                ('generated_palette', models.JSONField(blank=True, default=dict, help_text='Generated color palette')),
                ('generated_typography', models.JSONField(blank=True, default=dict, help_text='Generated typography suggestions')),
                ('generated_voice_examples', models.JSONField(blank=True, default=list, help_text='Brand voice examples')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Profile',
                'verbose_name_plural': 'Brand Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
