# Generated by Django 5.0.6 on 2026-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_brand_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='addons_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='guidelines_file',
            field=models.FileField(blank=True, null=True, upload_to='branding/deliverables/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='logo_final',
            field=models.FileField(blank=True, null=True, upload_to='branding/deliverables/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment Pending'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='selected_addons',
            field=models.JSONField(blank=True, default=list, help_text='List of OnboardingAddon slugs e.g. ["logo-addon", "brand-addon"]'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
