# Generated by Django 5.0.6 on 2026-09-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_brandprofile_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsession',
            name='package_type',
            field=models.CharField(blank=True, choices=[('startup', 'Startup Package'), ('essential', 'Basic Package')], help_text='Startup Package or Basic Package', max_length=20),
        ),
    ]
