# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_add_package_type_to_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingsession',
            name='package_type',
            field=models.CharField(blank=True, choices=[('startup', 'Startup Package'), ('essential', 'Basic Package'), ('enterprise', 'Enterprise Package')], help_text='Startup, Basic, or Enterprise Package', max_length=20),
        ),
    ]
