# Generated by Django 5.0.6 on 2026-08-19 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tag', models.CharField(choices=[('Data', 'Data'), ('Integration', 'Integration'), ('Automation', 'Automation'), ('ERP & CRM', 'ERP & CRM'), ('IoT', 'IoT')], default='Integration', max_length=50)),
                ('image', models.URLField(blank=True, help_text='Image URL or upload', max_length=500)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='blog/articles/')),
                ('service_url', models.CharField(blank=True, help_text='Django URL name for CTA link', max_length=255)),
                ('description', models.TextField(max_length=300)),
                ('content', models.TextField(help_text='HTML content for the article body')),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tag', models.CharField(choices=[('Tips', 'Tips'), ('Update', 'Update'), ('How-To', 'How-To'), ('News', 'News')], default='Tips', max_length=50)),
                ('image', models.URLField(blank=True, help_text='Image URL or upload', max_length=500)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('description', models.TextField(max_length=300)),
                ('content', models.TextField(help_text='HTML content for the blog post body')),
                ('read_time', models.CharField(default='3 min', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
