# Generated by Django 5.0.6 on 2026-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/articles/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/posts/'),
        ),
    ]
