# Generated by Django 5.0.6 on 2026-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_consultationrequest_user_websitebuildrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitebuildrequest',
            name='timeline',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
