# Generated by Django 5.0.6 on 2026-02-17 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_websitebuildrequest_timeline'),
    ]

    def generate_matricules(apps, schema_editor):
        ConsultationRequest = apps.get_model('home', 'ConsultationRequest')
        for obj in ConsultationRequest.objects.all():
            if not obj.matricule:
                base = uuid.uuid4().hex[:10].upper()
                matricule = f"C-{base}"
                while ConsultationRequest.objects.filter(matricule=matricule).exists():
                    base = uuid.uuid4().hex[:10].upper()
                    matricule = f"C-{base}"
                obj.matricule = matricule
                obj.save(update_fields=['matricule'])

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='matricule',
            field=models.CharField(blank=True, null=True, max_length=32),
        ),
        migrations.RunPython(generate_matricules, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='consultationrequest',
            name='matricule',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
