# Generated by Django 5.0.6 on 2026-01-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0027_kpihistory_avg_phase_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_stage', models.CharField(choices=[('LEAD', 'Lead'), ('QUALIFIED_LEAD', 'Qualified Lead'), ('ACTIVE_CLIENT', 'Active Client'), ('RETAINED_CLIENT', 'Retained Client'), ('CHURNED', 'Churned')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or Company name', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', max_length=20)),
                ('lifecycle_stage', models.CharField(choices=[('LEAD', 'Lead'), ('QUALIFIED_LEAD', 'Qualified Lead'), ('ACTIVE_CLIENT', 'Active Client'), ('RETAINED_CLIENT', 'Retained Client'), ('CHURNED', 'Churned')], default='LEAD', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='For individuals representing a company', max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Where did this customer come from?', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Link to the registered user account if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Phone Call'), ('MEETING', 'Meeting'), ('NOTE', 'Internal Note'), ('TICKET', 'Support Ticket'), ('SYSTEM', 'System Notification')], default='NOTE', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(help_text='e.g., Website, RPA, Branding', max_length=100)),
                ('description', models.TextField()),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under Review'), ('PROPOSAL', 'Proposal Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_request', to='projects.project')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('action_type', models.CharField(choices=[('EMAIL', 'Send Email'), ('TASK', 'Create Task'), ('NOTIFICATION', 'Send Notification')], max_length=20)),
                ('action_details', models.JSONField(help_text='Configuration for the action (e.g., email template, task title)')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.crmworkflow')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
    ]
