# Generated by Django 5.0.6 on 2026-02-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmworkflow',
            name='trigger_stage',
        ),
        migrations.AddField(
            model_name='crmworkflow',
            name='trigger_type',
            field=models.CharField(choices=[('LIFECYCLE_CHANGE', 'Lifecycle Stage Change'), ('HEALTH_SCORE_DROP', 'Health Score Drops Below'), ('HEALTH_SCORE_RISE', 'Health Score Rises Above'), ('INACTIVITY', 'No Interaction For (Days)'), ('INVOICE_OVERDUE', 'Invoice Overdue'), ('PROPOSAL_UPDATE', 'Proposal Status Change')], default='LIFECYCLE_CHANGE', max_length=30),
        ),
        migrations.AddField(
            model_name='crmworkflow',
            name='trigger_value',
            field=models.CharField(blank=True, help_text="Threshold value (e.g., '50' for score, '14' for days, 'ACTIVE' for stage)", max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_health_score',
            field=models.IntegerField(default=70, help_text='Calculated 0-100 score'),
        ),
        migrations.AddField(
            model_name='customer',
            name='health_trend',
            field=models.CharField(choices=[('UP', 'Improving'), ('DOWN', 'Declining'), ('STABLE', 'Stable')], default='STABLE', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_health_calc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='action_details',
            field=models.JSONField(help_text="Config: {'template': '...', 'title': '...', 'stage': '...'}"),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='action_type',
            field=models.CharField(choices=[('EMAIL', 'Send Email'), ('TASK', 'Create Task'), ('NOTIFICATION', 'Send Notification'), ('CHANGE_STAGE', 'Change Lifecycle Stage'), ('ASSIGN_USER', 'Assign/Reassign User'), ('CREATE_PROJECT', 'Create Project'), ('SCHEDULE_MEETING', 'Schedule Meeting')], max_length=20),
        ),
    ]
