# Generated by Django 5.0.6 on 2026-04-12 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_crmworkflow_trigger_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_customer_id', models.CharField(help_text='Customer ID in ERPNext', max_length=255)),
                ('erp_site_name', models.CharField(help_text='ERPNext site name', max_length=255)),
                ('api_key', models.CharField(help_text='Encrypted API key', max_length=255)),
                ('api_secret', models.CharField(help_text='Encrypted API secret', max_length=255)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('realtime_enabled', models.BooleanField(default=True, help_text='Enable real-time updates')),
                ('notification_email', models.EmailField(blank=True, help_text='Email for notifications', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Tracking',
                'verbose_name_plural': 'Client Tracking',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_STATUS', 'Order Status Changes'), ('INVOICE_DUE', 'Invoice Due Reminders'), ('PAYMENT_RECEIVED', 'Payment Confirmations'), ('DELIVERY_UPDATE', 'Delivery Updates'), ('SYSTEM_MAINTENANCE', 'System Maintenance')], max_length=50)),
                ('message', models.TextField()),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='crm.clienttracking')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_STATUS', 'Order Status Changes'), ('INVOICE_DUE', 'Invoice Due Reminders'), ('PAYMENT_RECEIVED', 'Payment Confirmations'), ('DELIVERY_UPDATE', 'Delivery Updates'), ('SYSTEM_MAINTENANCE', 'System Maintenance')], max_length=50)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm.clienttracking')),
            ],
            options={
                'verbose_name': 'Client Notification',
                'verbose_name_plural': 'Client Notifications',
                'unique_together': {('client', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_invoice_id', models.CharField(help_text='Invoice ID in ERPNext', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=50)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.clienttracking')),
            ],
            options={
                'verbose_name': 'Invoice Snapshot',
                'verbose_name_plural': 'Invoice Snapshots',
                'ordering': ['-issue_date'],
                'unique_together': {('client', 'erp_invoice_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_order_id', models.CharField(help_text='Order ID in ERPNext', max_length=255)),
                ('product', models.CharField(help_text='Product or service name', max_length=255)),
                ('qty', models.IntegerField(default=0, help_text='Quantity ordered')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=50)),
                ('progress_percent', models.IntegerField(default=0, help_text='Completion percentage')),
                ('target_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.clienttracking')),
            ],
            options={
                'verbose_name': 'Order Snapshot',
                'verbose_name_plural': 'Order Snapshots',
                'ordering': ['-last_updated'],
                'unique_together': {('client', 'erp_order_id')},
            },
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='ERPNext item code', max_length=255)),
                ('item_name', models.CharField(help_text='Item name', max_length=255)),
                ('allocated_qty', models.IntegerField(default=0, help_text='Quantity allocated to client')),
                ('available_qty', models.IntegerField(default=0, help_text='Total available quantity')),
                ('unit_rate', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_allocations', to='crm.clienttracking')),
            ],
            options={
                'verbose_name': 'Stock Allocation',
                'verbose_name_plural': 'Stock Allocations',
                'unique_together': {('client', 'item_code')},
            },
        ),
    ]
