# Generated by Django 5.0.6 on 2026-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_clienttracking_notificationlog_clientnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='erp_api_key',
            field=models.CharField(blank=True, help_text='ERPNext API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='erp_api_secret',
            field=models.CharField(blank=True, help_text='ERPNext API Secret', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='erp_site_name',
            field=models.CharField(blank=True, help_text="ERPNext site name (e.g., 'demo' for demo.erpnext.com)", max_length=100),
        ),
    ]
