"""
Django settings for websity_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# WeasyPrint / GTK+ path setup for Windows
GTK_PATH = r'C:\Program Files\GTK3-Runtime Win64\bin'
if os.path.exists(GTK_PATH):
    os.environ['PATH'] = GTK_PATH + os.pathsep + os.environ.get('PATH', '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SITE_URL for email links and absolute URIs
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment; fallback to insecure key only in development
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-bhg@b&btr99*q&4cs+2lb2*0@4)jf35(z_2q-b36ah1i-!gchb')

# SECURITY WARNING: don't run with debug turned on in production!
# Read from environment; default to True for local development
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# Parse ALLOWED_HOSTS from environment (comma-separated)
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,onwebapp.onrender.com"
).split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    # Project apps
    'home',
    'users',
    'services',
    'blog',
    'contact',
    'chatbot',
    'payments',
    'seo_analyzer',
    'projects',
    'platform_app',
    'platform_monitoring',
    'channels',
    'operations',
    'rpa_dashboard',
    'crm',
    'community',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',
    # Project apps (continued)
    'social_proof',
    'forum',
    'branding',
]

ASGI_APPLICATION = 'websity_project.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

REDIS_URL = os.environ.get('REDIS_URL') or os.environ.get('CELERY_BROKER_URL')

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'branding.api.pagination.BrandPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'EXCEPTION_HANDLER': 'branding.api.exceptions.custom_exception_handler',
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Websity Branding API',
    'DESCRIPTION': 'REST API for the Websity Branding Service — manage brand collections, project requests, messaging, notifications, and feedback.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Collections', 'description': 'Brand identity collection library'},
        {'name': 'Requests', 'description': 'Branding project requests (CRUD, assign, status)'},
        {'name': 'Assets', 'description': 'File uploads and deliverables'},
        {'name': 'Notifications', 'description': 'In-app notifications'},
        {'name': 'Messages', 'description': 'Threaded messaging between client and staff'},
        {'name': 'Timeline', 'description': 'Audit trail of events'},
        {'name': 'Feedback', 'description': 'Client feedback and ratings'},
        {'name': 'Auth', 'description': 'JWT authentication (token obtain, refresh, verify)'},
    ],
}

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

if DEBUG:
    MIDDLEWARE.insert(0, 'branding.middleware.QueryCountMiddleware')

# Rate limit middleware (after auth, before view processing)
MIDDLEWARE.append('branding.middleware.RateLimitMiddleware')

ROOT_URLCONF = 'websity_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'websity_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('ar', 'Arabic'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication redirects
LOGIN_REDIRECT_URL = 'users:onboarding'
LOGOUT_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ERP Integration Settings
ERP_GATEWAY_URL = os.environ.get('ERP_GATEWAY_URL', 'http://localhost:3000')
ERP_DOMAIN = os.environ.get('ERP_DOMAIN', 'onwebapp.com')

# Email configuration: read from environment when available. If EMAIL_HOST_USER/PASSWORD
# are not set, fall back to the console backend so developers see emails locally.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD and EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # Safe default for local dev: prints emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Stripe configuration - read from environment for safety. Empty values are allowed for local dev.
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Celery configuration - default to local Redis broker if not provided.
# To enable Celery usage in code, check USE_CELERY flag.
USE_CELERY = os.environ.get('USE_CELERY', 'False').lower() in ('1', 'true', 'yes')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_BEAT_SCHEDULE = {
    'collect-social-events-every-minute': {
        'task': 'social_proof.tasks.collect_social_events',
        'schedule': 60.0,
    },
    'update-crm-health-scores-every-hour': {
        'task': 'crm.tasks.update_all_customer_health_scores',
        'schedule': 3600.0, # Every hour
    },
    'calculate-template-metrics-daily': {
        'task': 'branding.tasks.calculate_template_metrics',
        'schedule': 86400.0,  # Every 24 hours
    },
    'scan-pending-assets-every-10-minutes': {
        'task': 'branding.tasks.scan_pending_assets',
        'schedule': 600.0,  # Every 10 minutes
    },
    'anonymize-expired-requests-daily': {
        'task': 'branding.tasks.anonymize_expired_requests',
        'schedule': 86400.0,  # Every 24 hours
    },
    'cleanup-expired-exports-daily': {
        'task': 'branding.tasks.cleanup_expired_exports',
        'schedule': 86400.0,  # Every 24 hours
    },
}

# ClamAV virus scanning configuration
CLAMAV_ENABLED = os.environ.get('CLAMAV_ENABLED', 'False').lower() in ('1', 'true', 'yes')
CLAMAV_HOST = os.environ.get('CLAMAV_HOST', '127.0.0.1')
CLAMAV_PORT = int(os.environ.get('CLAMAV_PORT', '3310'))
CLAMAV_TIMEOUT = int(os.environ.get('CLAMAV_TIMEOUT', '10'))

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'seo-progress-store',
        'TIMEOUT': 1800,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Per-site cache (used by UpdateCacheMiddleware / FetchFromCacheMiddleware)
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = 'branding_site'

# Use Redis cache if available
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# Query count logging (development only)
if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'branding.queries': {
                'handlers': ['console'],
                'level': 'DEBUG',
                'propagate': False,
            },
            'branding.security': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }

# ===== PRODUCTION HARDENING SETTINGS =====
# These settings enhance security and are recommended for production deployments.

# CSRF Settings
CSRF_COOKIE_SECURE = not DEBUG  # Only send CSRF cookie over HTTPS in production
CSRF_COOKIE_HTTPONLY = True    # Prevent JavaScript access to CSRF token
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Session Settings
SESSION_COOKIE_SECURE = not DEBUG  # Only send session cookie over HTTPS in production
SESSION_COOKIE_HTTPONLY = True    # Prevent JavaScript access to session
SESSION_COOKIE_SAMESITE = 'Lax'   # Prevent CSRF via cookies

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", 'cdn.jsdelivr.net'),
    'style-src': ("'self'", 'cdn.jsdelivr.net'),
    'img-src': ("'self'", 'data:'),
    'font-src': ("'self'", 'cdn.jsdelivr.net'),
}

# Force HTTPS and HSTS in production (when not DEBUG)
# ALWAYS disabled for local development to allow HTTP connections
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Sentry Configuration (Optional: for error tracking in production)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.1,
            send_default_pii=False,
            environment=os.environ.get('ENVIRONMENT', 'production'),
        )
    except ImportError:
        # Sentry SDK not installed; skip initialization
        pass


