# Generated by Django 5.0.6 on 2026-06-24 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Root URL to start crawling (must include http/https)', max_length=2000)),
                ('domain', models.CharField(blank=True, db_index=True, help_text='Extracted domain (www.example.com or example.com)', max_length=255, null=True)),
                ('max_pages', models.PositiveSmallIntegerField(default=50, help_text='Maximum number of pages to crawl (capped at 100 for MVP)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text="Only populated if status = 'failed'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the audit (null for anonymous/public demo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Audit Task',
                'verbose_name_plural': 'SEO Audit Tasks',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='SEOHistoricalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('health_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('technical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('on_page_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_historical_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Historical Report',
                'verbose_name_plural': 'SEO Historical Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOResult',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='result', serialize=False, to='seo_analyzer.seotask')),
                ('final_url', models.URLField(help_text='Final URL after redirects', max_length=2000)),
                ('https_status', models.BooleanField(default=False, help_text='True if root domain has valid, non-expired HTTPS certificate')),
                ('main_status_code', models.PositiveSmallIntegerField(help_text='HTTP status code of root URL')),
                ('main_response_time', models.FloatField(help_text='Root URL response time (seconds)')),
                ('health_score', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('technical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('on_page_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discovery_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ai_opportunity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('critical_issues', models.PositiveIntegerField(default=0)),
                ('high_issues', models.PositiveIntegerField(default=0)),
                ('medium_issues', models.PositiveIntegerField(default=0)),
                ('low_issues', models.PositiveIntegerField(default=0)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('internal_links_count', models.PositiveIntegerField(default=0)),
                ('broken_internal_links_count', models.PositiveIntegerField(default=0)),
                ('sitemap_entries_found', models.PositiveIntegerField(default=0)),
                ('orphan_pages_count', models.PositiveIntegerField(default=0)),
                ('redirect_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Audit Result',
                'verbose_name_plural': 'SEO Audit Results',
            },
        ),
        migrations.CreateModel(
            name='SEOPageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Original URL requested', max_length=2000)),
                ('final_url', models.URLField(blank=True, help_text='Final URL after redirects', max_length=2000, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time (seconds)', null=True)),
                ('page_size', models.PositiveIntegerField(blank=True, help_text='Page size (bytes)', null=True)),
                ('title_tag', models.TextField(blank=True, null=True)),
                ('title_tag_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_description_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('h1_count', models.PositiveSmallIntegerField(default=0)),
                ('h1_text', models.TextField(blank=True, null=True)),
                ('h2_count', models.PositiveSmallIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('has_canonical', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('is_noindex', models.BooleanField(default=False)),
                ('images_count', models.PositiveSmallIntegerField(default=0)),
                ('images_missing_alt', models.PositiveSmallIntegerField(default=0)),
                ('internal_links_count', models.PositiveIntegerField(default=0)),
                ('broken_internal_links_count', models.PositiveIntegerField(default=0)),
                ('has_robots', models.BooleanField(default=False)),
                ('has_sitemap', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_audits', to='seo_analyzer.seotask')),
            ],
            options={
                'verbose_name': 'Page Audit',
                'verbose_name_plural': 'Page Audits',
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='SEOIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('on-page', 'On-Page SEO'), ('technical', 'Technical SEO'), ('performance', 'Performance'), ('discovery', 'Discovery')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('seo_impact', models.TextField(blank=True, null=True)),
                ('business_impact', models.TextField(blank=True, null=True)),
                ('recommended_fix', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_audit', models.ForeignKey(blank=True, help_text='Null if issue is audit-wide (not page-specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='seo_analyzer.seopageaudit')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='seo_analyzer.seotask')),
            ],
            options={
                'verbose_name': 'SEO Issue',
                'verbose_name_plural': 'SEO Issues',
                'ordering': [models.Case(models.When(severity='critical', then=0), models.When(severity='high', then=1), models.When(severity='medium', then=2), models.When(severity='low', then=3), default=4, output_field=models.IntegerField()), '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='seopageaudit',
            constraint=models.UniqueConstraint(fields=('task', 'final_url'), name='unique_page_per_task_final_url'),
        ),
        migrations.AddConstraint(
            model_name='seoissue',
            constraint=models.UniqueConstraint(fields=('task', 'page_audit', 'name'), name='unique_issue_per_task_page'),
        ),
    ]
