# Generated by Django 5.0.6 on 2026-06-28 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEONotificationEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('channel_type', models.CharField(choices=[('email', 'Email Alerts'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('webhook', 'Webhook')], max_length=20)),
                ('destination', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_notification_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Notification Endpoint',
                'verbose_name_plural': 'SEO Notification Endpoints',
                'ordering': ['domain', 'channel_type'],
            },
        ),
        migrations.CreateModel(
            name='SEOMonitoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_identifier', models.CharField(max_length=64, unique=True)),
                ('website', models.URLField(max_length=2000)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('analysis_type', models.CharField(choices=[('website', 'Website Checker'), ('internal', 'Internal Links'), ('external', 'External Links'), ('backlinks', 'Backlinks')], db_index=True, default='website', max_length=20)),
                ('health_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('visibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_opportunity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('content_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('security_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('broken_links', models.PositiveIntegerField(blank=True, null=True)),
                ('redirects', models.PositiveIntegerField(blank=True, null=True)),
                ('internal_links', models.PositiveIntegerField(blank=True, null=True)),
                ('external_links', models.PositiveIntegerField(blank=True, null=True)),
                ('indexed_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('issues_count', models.PositiveIntegerField(blank=True, null=True)),
                ('working_links', models.PositiveIntegerField(blank=True, null=True)),
                ('errors_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tracked_items', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_monitoring_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Monitoring Snapshot',
                'verbose_name_plural': 'SEO Monitoring Snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'analysis_type', '-created_at'], name='seo_analyze_domain_1eff54_idx')],
            },
        ),
    ]
