# Generated by Django 5.0.6 on 2026-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0003_urlintelligencetask_urlintelligenceresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlintelligenceresult',
            name='canonical_status',
            field=models.CharField(choices=[('self', 'Self-Canonical'), ('other', 'Canonical to Another URL'), ('missing', 'Canonical Missing'), ('conflict', 'Canonical Conflict'), ('not_evaluated', 'Not Evaluated'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='urlintelligenceresult',
            name='indexability_status',
            field=models.CharField(choices=[('indexable', 'Indexable'), ('noindex', 'Noindex'), ('blocked', 'Blocked'), ('redirected', 'Redirected'), ('not_evaluated_auth_required', 'Not Evaluated — Authentication Required'), ('not_evaluated_access_restricted', 'Not Evaluated — Access Restricted'), ('not_evaluated_rate_limited', 'Not Evaluated — Rate Limited'), ('not_found', 'Not Indexable — Not Found'), ('gone', 'Not Indexable — Gone'), ('server_error', 'Temporarily Unavailable — Server Error'), ('error', 'Error'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=40),
        ),
    ]
