# Generated by Django 5.0.6 on 2026-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0004_alter_urlintelligenceresult_canonical_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopageaudit',
            name='has_video_schema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seopageaudit',
            name='images_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='seopageaudit',
            name='videos_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seopageaudit',
            name='videos_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
